### ISSUE TITLE
是否可以动态演示？

### ISSUE THREAD

**Issue by cevio** [fengyuanchen/markdown-to-vue-loader#1]
看了下，好像无法动态演示。是不是只是将HTML渲染出来而已，比如说双向流数据变化等无法体现出来。而且用的是template，不是render。感觉只完成了一部分。作者是否考虑过动态演示？

**Comment by fengyuanchen** [comment]
什么叫动态演示？双向流数据变化是Vue本身的功能，跟这个loader没有什么关系吧？
