### ISSUE TITLE
vue3 typescript 提示

### ISSUE THREAD

**Issue by songjiachao** [fengyuanchen/markdown-to-vue-loader#7]
this.getOptions is not a function

**Comment by songjiachao** [comment]
可以帮忙看下吗？
![image](https://user-images.githubusercontent.com/70792885/115008820-2e33b100-9ede-11eb-884e-ade217fadff5.png)

**Comment by fengyuanchen** [comment]
If you are using Webpack 4, then you should install the v2 versions.
If you are using Webpack 5, then you should install the v3 versions.

**Comment by songjiachao** [comment]
![image](https://user-images.githubusercontent.com/70792885/115172272-7e399000-a0f7-11eb-8a29-b4c89ce388e7.png)

when I use v2 versions, another error happen

**Comment by fengyuanchen** [comment]
You may need to bust the webpack cache:

```shell
rm -rf ./node_modules
npm install
```
