### ISSUE TITLE
You may need an additional loader to handle the result of these loaders

### ISSUE THREAD

**Issue by jannikbuscha** [fengyuanchen/markdown-to-vue-loader#8]
Hi, I get this error:
![image](https://user-images.githubusercontent.com/74017697/138679143-b28b7a1b-4b0e-4b99-a1d2-1bfc5c7be18f.png)

My vue.config.js:
![image](https://user-images.githubusercontent.com/74017697/138679175-761b8c3e-fd40-4fbb-b124-c81084d933aa.png)

My package.json:
![image](https://user-images.githubusercontent.com/74017697/138679233-dfa8da56-3c18-4175-9a97-467302af9807.png)

My vue component:
![image](https://user-images.githubusercontent.com/74017697/138679285-6d33e5fb-8027-4ad5-bf79-f469e551f1cc.png)

**Comment by fengyuanchen** [comment]
There is a breaking change as of `vue-loader@16.6.0`, see [this issue](https://github.com/vuejs/vue-loader/issues/1883).

For a quick fix, you can lock the `vue-loader` version to 16.5.0:

```sh
npm install vue-loader@16.5.0
```

**Comment by fengyuanchen** [comment]
Fixed in `vue-loader@16.8.2`.
